version: '3.4'

services:
  webassemblytest.server:
    image: ${DOCKER_REGISTRY-}webassemblytestserver
    build:
      context: .
      dockerfile: Server/Dockerfile

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "8888:80"
    volumes:
      - /datadrive:/data
    environment:
      - ACCEPT_EULA=Y